require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cmses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Cmse. As you add validations to Cmse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cmse.create! valid_attributes
      get cmses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cmse = Cmse.create! valid_attributes
      get cmse_url(cmse)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cmse_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cmse = Cmse.create! valid_attributes
      get edit_cmse_url(cmse)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cmse" do
        expect {
          post cmses_url, params: { cmse: valid_attributes }
        }.to change(Cmse, :count).by(1)
      end

      it "redirects to the created cmse" do
        post cmses_url, params: { cmse: valid_attributes }
        expect(response).to redirect_to(cmse_url(Cmse.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cmse" do
        expect {
          post cmses_url, params: { cmse: invalid_attributes }
        }.to change(Cmse, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cmses_url, params: { cmse: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cmse" do
        cmse = Cmse.create! valid_attributes
        patch cmse_url(cmse), params: { cmse: new_attributes }
        cmse.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cmse" do
        cmse = Cmse.create! valid_attributes
        patch cmse_url(cmse), params: { cmse: new_attributes }
        cmse.reload
        expect(response).to redirect_to(cmse_url(cmse))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cmse = Cmse.create! valid_attributes
        patch cmse_url(cmse), params: { cmse: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cmse" do
      cmse = Cmse.create! valid_attributes
      expect {
        delete cmse_url(cmse)
      }.to change(Cmse, :count).by(-1)
    end

    it "redirects to the cmses list" do
      cmse = Cmse.create! valid_attributes
      delete cmse_url(cmse)
      expect(response).to redirect_to(cmses_url)
    end
  end
end
