require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/page_sections', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # PageSection. As you add validations to PageSection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      PageSection.create! valid_attributes
      get page_sections_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      page_section = PageSection.create! valid_attributes
      get page_section_url(page_section)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_page_section_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      page_section = PageSection.create! valid_attributes
      get edit_page_section_url(page_section)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new PageSection' do
        expect do
          post page_sections_url, params: { page_section: valid_attributes }
        end.to change(PageSection, :count).by(1)
      end

      it 'redirects to the created page_section' do
        post page_sections_url, params: { page_section: valid_attributes }
        expect(response).to redirect_to(page_section_url(PageSection.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new PageSection' do
        expect do
          post page_sections_url, params: { page_section: invalid_attributes }
        end.to change(PageSection, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post page_sections_url, params: { page_section: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested page_section' do
        page_section = PageSection.create! valid_attributes
        patch page_section_url(page_section), params: { page_section: new_attributes }
        page_section.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the page_section' do
        page_section = PageSection.create! valid_attributes
        patch page_section_url(page_section), params: { page_section: new_attributes }
        page_section.reload
        expect(response).to redirect_to(page_section_url(page_section))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        page_section = PageSection.create! valid_attributes
        patch page_section_url(page_section), params: { page_section: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested page_section' do
      page_section = PageSection.create! valid_attributes
      expect do
        delete page_section_url(page_section)
      end.to change(PageSection, :count).by(-1)
    end

    it 'redirects to the page_sections list' do
      page_section = PageSection.create! valid_attributes
      delete page_section_url(page_section)
      expect(response).to redirect_to(page_sections_url)
    end
  end
end
